### ISSUE TITLE
eb - command not found

### ISSUE THREAD

**Issue by andrewtennison** [cliftonc/express-mvc-bootstrap#17]
probably being very thick, the project does not work on latest versions of node, but i love the setup of it so am trying to replciate a few elements in a new project. 

From project directory typing ed = command not found. Is it dependent on another plugin or module I may have not setup, possibly that would be installed with npm install express-mvc-bootstrap?

Thanks for any assistance

**Comment by cliftonc** [comment]
Hi, you need to make sure you do an 'npm install -g', as this creates a
link to the script in the ./bin folder.

Otherwise just do ./bin/eb from the root of the project?

Clifton

On 5 May 2012 15:50, andrewtennison <
reply@reply.github.com

**Comment by andrewtennison** [comment]
was being a bit thick, just investigated further and realised that eb is a JS file, so "node eb" is required to run it. I now just have the issue I cannot install globally due to compatibility issues with node, but I can investigate further how to replicate some of the functionality within the project. Thanks

**Comment by cliftonc** [comment]
Apologies, been a while since I looked at this project.

eb is actually in the root folder of the project, not bin, but is
referenced in the package.json folder and so if installed via the 'npm
install -g' route, there should be a simlink created in your NodeJS bin
folder (wherever you have node installed).

To get it working I would try:
- Git clone github
- 'npm install -d'
- Fix any failures (e.g. increase version numbers inside the package.json
  for anything that doesn't work, including the NodeJS engine version).
- If that doesn't work it is probably something more serious!

Clifton

On 8 May 2012 16:38, andrewtennison <
reply@reply.github.com

**Comment by andrewtennison** [comment]
there were a lot of issues with tests due to compatibility. I have had to upgrade my version to mocha, hopefully I will have a chance later this week to do some updates and create a pull. cheers Andy

**Comment by salmansqadeer** [comment]
Im having this issue as well, and note sure how to resolve it.  I have done the "npm install -g" with no errors being reported, but whenever I run eb I still get command not found.  Would love to know how to fix this since this looks like exactly what I was looking for.

Thanks in advance!
