### ISSUE TITLE
Is it possible to regenerate MVC or pass in a schema when generating?

### ISSUE THREAD

**Issue by jacobSingh** [cliftonc/express-mvc-bootstrap#5]
This would be wicked of course, ala rails, etc.
From what I can tell, you get the scaffolding for free with a "name" attribute and then you have to do the rest.  Is this a feature request or me not RTFM?

**Comment by cliftonc** [comment]
It's a feature request, you're not missing anything!   We basically need to add the code into the create controller and create view scripts that scans the properties of the domain schema, and generates the code as required.

Happy for you to take a crack at it, otherwise it was something that was on my list, but wasn't sure how important it was, so was going to get around to it eventually!

Clifton
